In [16]:
from board import *

x = Board((2, 2, 2))
x.populate_randomly(99)
x.update_token_history()
x.populate_randomly(99)
x.update_token_history()

print(x.token_history[1:3])

arr = np.roll(x.token_history, -x.token_history_i, axis=0)[-2:]

def get_lines(arr):
    # arr : an nxnxnxn subarray of the full array of tokens for connections of length n

    
    for orientation in range(4):
        line_slice = lambda i, j, k : np.roll([i,j,k,slice(None)], orientation)
        plane_slice1 = lambda i, j : np.roll([i,j,slice(None),slice(None)], orientation)
        plane_slice2 = lambda i, j : np.roll([i,slice(None),j,slice(None)], orientation)
        for i in range(arr.shape[orientation]):
            # cubes
            for j in range(arr.shape[(orientation+1) % 4]):
                # planes
                print(plane_slice1(i, j))
                yield arr[plane_slice1(i, j)].diagonal()
                yield arr[plane_slice2(i, j)].diagonal()
                for k in range(arr.shape[(orientation+2) % 4]):
                    # lines
                    yield arr[line_slice(i, j, k)]

    # 2d diagonals
    for orientation in range(3):
        s = lambda i, j : np.roll([i,j,slice(None),slice(None)], orientation)
        for i in range(arr.shape[orientation]):
            for j in range(arr.shape[(orientation+1) % 3]):
                    a,b,c = s(i,j,k)
                    yield arr[a,b,:].diagonal()
        

#arr[0,:,:,:].diagonal()[0] # 3d diagonals???
# 4d diagonals???

for line in get_lines(arr):
    print(line)

[[[[11 17]
   [54 70]]

  [[98 20]
   [17 89]]]


 [[[63  1]
   [77 14]]

  [[56 55]
   [58 64]]]]


IndexError: arrays used as indices must be of integer (or boolean) type

In [7]:
from board import *

x = Board((4,4,4))

x.place(Token.red, (0,0))

x.place(Token.red, (0,1))

x.place(Token.red, (0,2))

x.place(Token.red, (0,3))
#print(x.tokens)



array([0, 0, 0, 0], dtype=uint8)

In [ ]:

from board import *

x = Board((4,4,4))
x.populate_randomly()

#print(x.tokens)

x.apply_gravity()

#print(x.tokens)

x.place(Token.debug, (0,0), Gravity.right)

print(x.tokens)

gravity applied
gravity applied
placing 99 at (0, 0, slice(None, None, None)) in row [0 0 0 0]
placed 99 at (0, 0, slice(None, None, None)):TOP
gravity applied
[[[ 0  0  0 99]
  [ 0  0  0  3]
  [ 0  0  1  1]
  [ 0  0  0  0]]

 [[ 0  0  3  3]
  [ 0  1  3  2]
  [ 0  2  1  1]
  [ 0  0  0  0]]

 [[ 1  1  3  3]
  [ 1  3  2  2]
  [ 3  1  2  2]
  [ 2  3  1  1]]

 [[ 1  3  2  3]
  [ 2  1  1  2]
  [ 3  2  3  1]
  [ 1  2  2  2]]]
